version: "3.3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - myapp-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - myapp-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
